# Generated by Django 5.2.8 on 2025-11-18 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='atleta',
            old_name='esporte',
            new_name='modalidade',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='atletica',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='atletica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atletica',
            name='instagram',
        ),
        migrations.AddField(
            model_name='atleta',
            name='ano_entrada',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='desempenho',
            field=models.TextField(blank=True, help_text='Descrição de desempenho que o atleta pode escrever.'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_atleta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atletica',
            name='ano_fundacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atletica',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atleticas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atletica',
            name='universidade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
