# Generated by Django 5.2.7 on 2025-11-22 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_rename_esporte_atleta_modalidade_remove_atleta_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateField(default=django.utils.timezone.now)),
                ('modalidade', models.CharField(max_length=100)),
                ('atletica_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_1', to='staticpages.atletica', verbose_name='Atlética 1')),
                ('atletica_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_2', to='staticpages.atletica', verbose_name='Atlética 2')),
                ('atletica_vencedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitorias', to='staticpages.atletica', verbose_name='Atlética Vencedora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('atletica_1', models.F('atletica_2')), _negated=True), name='atletica_diferente')],
            },
        ),
    ]
